# Generated by Django 3.2.9 on 2021-12-05 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20211205_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='content_list', to='movies.streamingplatform'),
            preserve_default=False,
        ),
    ]
